### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by jsalatiel** [Yepkit/ykurcmd#1]
After a few executions, i start getting segfaults until i restart the computer. 
Running debian 8 jessie

Any fixes ?

```
Starting program: /tmp/ykurcmd/ykurcmd/bin/ykurcmd -u r
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bda5f7 in hid_set_nonblocking () from /usr/lib/x86_64-linux-gnu/libhidapi-hidraw.so.0
(gdb) bt
#0  0x00007ffff7bda5f7 in hid_set_nonblocking () from /usr/lib/x86_64-linux-gnu/libhidapi-hidraw.so.0
#1  0x0000000000401331 in command(char, char) ()
#2  0x000000000040106f in commandParser(int, char**) ()
#3  0x0000000000400b06 in main ()
(gdb) quit

```

**Comment by yep1** [comment]
Hi,

thanks for pointing this to us.

We will look into this now and provide feedback as soon as possible.

Best Regards,
Paulo

www.yepkit.com <http://www.yepkit.com>


DISCLAIMER

This e-mail, including any attachments, may contain confidential 
information for exclusive use of its recipient. If you are not the 
intended recipient you must not use, distribute or copy this e-mail. If 
you have received this e-mail in error please notify the sender and 
delete it immediately. Thank You.

Please consider the environment before printing this message. The 
environment thanks you.

AVISO

Esta mensagem, incluindo quaisquer anexos, pode conter informação 
confidencial para uso exclusivo do destinatário. Se não for o 
destinatário pretendido não deverá usar, distribuir ou copiar este 
e-mail. Se recebeu esta mensagem por engano, por favor informe o emissor 
e elimine-a imediatamente. Obrigado.

Por favor considere o ambiente antes de imprimir esta mensagem. O 
ambiente agradece.




------------------------------------------------------------------------
*From:* jsalatiel <notifications@github.com>
*Sent:* Saturday, May 13, 2017 11:20 AM GMT
*To:* Yepkit/ykurcmd <ykurcmd@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [Yepkit/ykurcmd] segmentation fault (#1)

**Comment by yep1** [comment]
Hi,

does the issue persists with the latest committed version, that uses the libusb backend?

Thanks.

**Comment by jsalatiel** [comment]
Sorry , i missed this comment.
I just checkout from git and it is not working at all.
It is not segfaulting anymore, but the relay is not being opened/closed. 
This is being printed to stdout
buf[0]: 1
buf[1]: 16
buf[2]: 17
buf[3]: 24
buf[4]: 38
buf[5]: 157
buf[6]: 80
buf[7]: 6
buf[8]: 25
buf[9]: 132
buf[10]: 57
buf[11]: 32
buf[12]: 126
buf[13]: 128
buf[14]: 17
buf[15]: 173
buf[16]: 33
buf[17]: 10
buf[18]: 53
buf[19]: 9
buf[20]: 68
buf[21]: 182
buf[22]: 68
buf[23]: 3
buf[24]: 204
buf[25]: 20
buf[26]: 74
buf[27]: 2
buf[28]: 35
buf[29]: 33
buf[30]: 196
buf[31]: 0
buf[32]: 10
buf[33]: 132
buf[34]: 56
buf[35]: 203
buf[36]: 16
buf[37]: 206
buf[38]: 17
buf[39]: 132
buf[40]: 23
buf[41]: 64
buf[42]: 79
buf[43]: 112
buf[44]: 136
buf[45]: 74
buf[46]: 25
buf[47]: 88
buf[48]: 32
buf[49]: 79
buf[50]: 66
buf[51]: 50
buf[52]: 214
buf[53]: 144
buf[54]: 138
buf[55]: 32
buf[56]: 17
buf[57]: 96
buf[58]: 1
buf[59]: 200
buf[60]: 152
buf[61]: 230
buf[62]: 25
buf[63]: 86

**Comment by yep1** [comment]
Hi,
that output was a debug print that should have been removed. We just did a new commit with the fix.

But the relay not switching is strange. If you run the following command: 

ykushcmd -u a

the external ports LEDs (4 LEDs) are turned on?

Best Regards
